### ISSUE TITLE
Proxy requires missing from app.js

### ISSUE THREAD

**Issue by krisadler-ge** [PredixDev/predix-nodejs-starter#1]
There are references to HttpsProxyAgent and proxyMiddleware in app.js, but those packages aren't ever fetched with require. They're also missing from the package.json.

```
var HttpsProxyAgent = require('https-proxy-agent');
var proxyMiddleware = require('http-proxy-middleware');
```

```
"http-proxy-middleware": "^0.10.0",
"https-proxy-agent": "^1.0.0",
```

**Comment by swapnavad** [comment]
yes, I am seeing this issue,will update the code.

**Comment by swapnavad** [comment]
This issue is now fixed,caused during migration.Please let us know if you see any issue deploying the app.
